[package]
name = "signum-miner"
version = "1.8.1"
license = "GPL-3.0"
authors = ["signum-network, forked from PoC Consortium"]
description = """
A fast and flexible miner for the Signum blockchain.
"""
build = "build.rs"
repository = "https://github.com/signum-network/signum-miner"
documentation = "https://github.com/signum-network/signum-miner"
keywords = ["poc", "miner", "rust","cryptocurrency"]
readme = "README.md"
edition = "2021"

[features]
simd = []
neon = []
opencl = ["ocl-core"]

[dependencies]
cfg-if = "0.1"
clap = "4.5.37"
core_affinity = "0.8.3"
crossbeam-channel = "0.5"
filetime = "0.2"
futures = "0.3"
hex = "0.3"
hostname = "0.4.1"
libc = "0.2"
log = "0.4"
log4rs = { version = "1.3", features = ["rolling_file_appender", "compound_policy", "size_trigger", "fixed_window_roller"] }
num_cpus = "1.9"
ocl-core = { version = "0.11.5", optional = true } 
pbr = "1.0.1"
rand = "0.6"
rayon = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
stopwatch = "0.0.7"
tokio = "0.1"
url = "1.7"
page_size = "0.6.0"
reqwest = { version = "0.9.9", default-features = false, features = ["rustls-tls"] }
bytes = "0.4.11"
url_serde = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["fileapi"] }

[build-dependencies]
cc = "1.0"
cfg-if = "0.1"

[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic
